version: "3"

services:
  api:
    build: .
    # ports:
    #   - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000
